version: '3.9'
services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'wasupstudio-db'
      MYSQL_ROOT_PASSWORD: '111111'
    volumes:
        - ./sql:/docker-entrypoint-initdb.d
        - ../mysql-data:/var/lib/mysql
  admin:
     image: adminer
     ports:
       - 8888:8080

  wasupstudio-service:
    image: aibolee/wasupstudio:latest
    ports:
      - 8080:8080

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:8080"
#    volumes:
#      - ../nginx.conf:/etc/nginx/conf.d


