FROM aibolee/dockerhub:paul-wasupstudio as build

FROM openjdk:8-jre
COPY --from=build /app/target/wasupstudio-0.0.1-SNAPSHOT.jar .
COPY ./entrypoint.sh .
RUN chmod +x entrypoint.sh

ENTRYPOINT [ "./entrypoint.sh" ]
