version: '3.9'
services:
  mysql:
    container_name: mysql_wa
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'wasupstudio-db'
      MYSQL_ROOT_PASSWORD: '*#^$FGHKJB!jk'
    volumes:
        - ./sql:/docker-entrypoint-initdb.d
        - ../mysql-data:/var/lib/mysql
  admin:
    container_name: admin_wa
    image: adminer
    ports:
       - 8888:8080

  wasupstudio-service:
    container_name: wasupstudio_wa
    image: aibolee/wasupstudio:latest
    ports:
      - 8080:8080

  nginx:
    container_name: nginx_wa
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../nginx.conf:/etc/nginx/conf.d


