FROM maven:3.6.3-openjdk-8 as build
WORKDIR /app
COPY . .
RUN mvn package


FROM openjdk:8-jre
COPY --from=build /app/target/paulDemo-0.0.1-SNAPSHOT.jar .
COPY entrypoint.sh .
RUN chmod +x entrypoint.sh

CMD [ "bash", "./entrypoint.sh" ]


