version: '3.9'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: your_mysql_database
      MYSQL_USER: your_mysql_user
      MYSQL_PASSWORD: your_mysql_password
    volumes:
      - ./mysql-data:/var/lib/mysql
  admin:
     image: adminer
     ports:
       - 8888:8080
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  wasupstudio-service:
     # 不同OS要注意
     build:
       dockerfile: ./dockerfile-mac
     ports:
       - 8080:8080
